<?php get_header();?>
<?php View::render('partials/section1')?>
<?php View::render('partials/about');?>
<?php View::render('partials/services');?>
<?php View::render('partials/portfolio');?>
<?php View::render('partials/pricing-plan');?>
<?php View::render('partials/team');?>
<?php View::render('partials/Testimonial');?>
<?php View::render('partials/Contact');?>
<?php get_footer();?>